# Generated by Django 5.2 on 2025-05-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesscode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoview',
            unique_together=set(),
        ),
    ]
