# Generated by Django 5.2 on 2025-05-06 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_videoview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
