# Generated by Django 5.2 on 2025-05-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_teacherreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الكود (30 يوم من تاريخ الاستخدام)', null=True),
        ),
    ]
