# Generated by Django 5.2 on 2025-05-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='specific_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_notifications', to='core.grade'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='specific_users',
            field=models.ManyToManyField(blank=True, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
