# Generated by Django 5.2 on 2025-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_specific_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='صورة غلاف الدرس', null=True, upload_to='lesson_thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='صورة غلاف كبيرة للفيديو (ستظهر في صفحة تفاصيل الفيديو)', null=True, upload_to='video_covers/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='صورة غلاف الفيديو (ستظهر في قائمة الفيديوهات)', null=True, upload_to='video_thumbnails/'),
        ),
    ]
