# Generated by Django 5.2 on 2025-05-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='core.video'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الكود (يستخدم مرة واحدة فقط)', null=True),
        ),
    ]
