# Generated by Django 5.2 on 2025-05-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_accesscode_video_alter_accesscode_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVideoAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('access_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_access_records', to='core.accesscode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_access_records', to='core.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_access_records', to='core.video')),
            ],
            options={
                'ordering': ['-access_date'],
                'unique_together': {('student', 'video')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='accessed_videos',
            field=models.ManyToManyField(related_name='accessed_by_students', through='core.StudentVideoAccess', to='core.video'),
        ),
    ]
