# Generated by Django 5.2 on 2025-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_studentvideoaccess_student_accessed_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='code_type',
            field=models.CharField(choices=[('video', 'كود فيديو'), ('course', 'كود كورس'), ('single', 'كود فيديو واحد فقط')], default='video', help_text='نوع الكود', max_length=10),
        ),
    ]
